version: '3.8'

services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - JWT_SERVICE_SECRET=JIHAEZNKQS456EF456H4635456654DRHJV
      - JWT_EXPIRATION=1d
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - USERS_SERVICE_URL=users-service:5052
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5


  users-service:
    build:
      context: ../users-microservice
      dockerfile: Dockerfile
    ports:
      - "5052:5052"
      - "5002:5002"
    environment:
      - NODE_ENV=development
    depends_on:
      - redis

volumes:
  redis_data:
